language: python
python:
- '3.7'
install:
- make build
script: make test
deploy:
  provider: pypi
  user: __token__
  on:
    tags: true
    python: '3.7'
    condition: "$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+[a-z]?$"
    repo: Nextdoor/tornado_rest_client
  password:
    secure: dw2pRS9GzLUBa+Ke5QBWSsnUm2ehGJUgvz9SEGIgB5MPFMziOWFW4A/ssOEnDISjbr6Ug7KnxyXpX0rt66OZNdA4+JO5wHTCt1snGRRdylu0tHgvAkshnfOKFJRUgNWcR+rkWrCFz91r8RHR7aidXka/ldRgBGgpwJyMHZzF0QUkds75e8OsZUt2ntsJbRXBz7b+CkG1jRFPQE0Z0TdP1zUuv1UIl0kGAMrWmz5e7W3Lsii48n6x0zUNqPboqr/k8E+yGb79wkPPh4cbCNnKT3IhxCvTyXQseP9QjOOwuG6u3faaMjwAbJbLcDDf7bXZKVGq5TdHD+cbEw+G6dDiV5aYhVObdxh5w5LLj36CH9ydGGSzT2CY4sHAQYcjfaeohiUDNFFb1gDrtIEPHMyDi9Q96XvWTecAKKWvONz2nek1NMqhNZWVXX3HoHU3ncHvuTzYk7R2sovL3+oSrKM1hKoUFuawY0fmXw2+hGse5O0av+Tn02fjDaHbV881dIXRQPb04nhziI5i39+ZLGzDPQWF5w4zBzDfiJK++c3zG+VKTLCUSGi5vbnqu+RroYqwDbzKRM7GYV8atV7NGnVbrqEoNi91fWfXzw4fghO4t5UfZTst0+ER7yJdxS3MucfyiRnI7M15O6tNfodC3B/xraKGkkhUmsH2h9HARF8VwQI=
