name: publish-release
on:
  release:
    types:
      - published
jobs:
  deploy:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=1cpu-linux-x64
      - extras=s3-cache
    steps:
    - name: Magic Cache
      uses: runs-on/action@v1
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@20d40f69a1d306453777ffecb5a86860e850ba0f
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
