name: test
on:
  pull_request: {}
jobs:
  pre-merge:
    name: Pre-Merge Checks
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=1cpu-linux-x64
      - extras=s3-cache
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Magic Cache
        uses: runs-on/action@v1

      - name: Checkout All
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python

      - name: Run make lint
        run: make lint
        shell: bash

      - name: Run make test
        run: make test
        shell: bash
        env:
          USER: bogus-string

      - name: Run make build
        run: make build
        shell: bash
